routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/**
 * BIG FREAKING NOTE
 * All the route name must be as CAMEL CASE
 * With the route only to show page (which return view), name it as: {name}Page (Example: loginPage)
 * With the route that receive action (POST, PUT,...), name it as: {name}Action (Example: loginAction)
 */

Route::get('/', function () {
    return redirect(config('bedone.DEFAULT_URL_LOGGED'));
});


// Authentication Routing
Route::get('/login', 'AuthenticationController@login')->name('loginPage');
Route::post('/doLogin', 'AuthenticationController@logging')->name('loginAction');
Route::get('/register', 'AuthenticationController@register')->name('registerPage');
Route::post('/doRegister', 'AuthenticationController@registering')->name('registerAction');
Route::get('/forgot', 'AuthenticationController@forgot')->name('forgotPage');
Route::post('/doForgot', 'AuthenticationController@forgotting')->name('forgotAction');
Route::get('/logout', 'UserController@logout')->name('logoutAction');
Route::get('/forgot/{key}', 'AuthenticationController@retrievePass')->name('userRetrievePassPage');
Route::post('/forgot_password/{key}', 'AuthenticationController@doRetrievePass')->name('userRetrievePassAction');

/**
 * User Profile Routing
 */
Route::get('/UserProfile/{id?}', 'UserController@UserProfile')->name('userProfilePage');
Route::get('/EditProfile', 'UserController@EditProfile')->name('editProfilePage');
Route::post('/EditProfile', 'UserController@EditingProfile')->name('editProfileAction');
Route::get('/Company/ResendRequest', 'UserController@ResendRequest')->name('resendRequestAction');
Route::get('/Company/CancelRequest', 'UserController@CancelRequest')->name('cancelRequestAction');

/**
 * User Setting
 */
Route::get('/Setting', 'UserController@setting')->name('settingPage');
Route::post('/Setting/ChangePassword', 'UserController@changePassword')->name('changePasswordAction');
Route::post('/Setting/ChangePrivacy', 'UserController@changeSetting')->name('changePrivacyAction');

/**
 * Company Info
 */
Route::get('/Company', 'CompanyModule\CompanyController@ViewCompany')->name('companyPage');
Route::get('/Company/Edit', 'CompanyModule\CompanyController@EditCompany')->name('editCompanyPage');
Route::post('/Company/Edit', 'CompanyModule\CompanyController@EditingCompany')->name('editCompanyAction');
Route::get('/Company/Leave', 'CompanyModule\CompanyController@leaving_company')->name('leaveCompanyAction');

/**
 * News Maintenance
 */
Route::get('/NewsMaintenance', 'NewsModule\NewsCategoryController@index')->name('newsMaintenancePage');
Route::get('/NewsMaintenance/Edit/{id}', 'NewsModule\NewsCategoryController@edit')->name('editNewsMaintenancePage');
Route::post('/NewsMaintenance/Edit/{id}', 'NewsModule\NewsCategoryController@editing')->name('editNewsMaintenanceAction');
Route::get('/NewsMaintenance/Add', 'NewsModule\NewsCategoryController@add')->name('addNewsMaintenancePage');
Route::post('/NewsMaintenance/Add', 'NewsModule\NewsCategoryController@adding')->name('addNewsMaintenanceAction');
Route::get('/NewsMaintenance/Delete/{id}', 'NewsModule\NewsCategoryController@DeleteCategory')->name('deleteNewsMaintenanceAction');

/**
 * New page
 */
Route::get('/News', 'NewsModule\NewsFeedController@index')->name('newsPage');
Route::get('/News/{id}', 'NewsModule\NewsFeedController@viewNews')->name('viewNewsPage');

/**
 * All staffs
 */
Route::get('/AllStaffs', 'MyNetworkModule\AllStaffController@index')->name('allStaffPage');

/**
 * Group
 */
Route::get('/Groups', 'MyNetworkModule\GroupController@index')->name('groupPage');
Route::get('/Groups/Info/{group_id}', 'MyNetworkModule\GroupController@view')->name('groupInfoPage');
Route::get('/Groups/RemoveMember/{group_id}/{user_id}', 'MyNetworkModule\GroupController@removeMember')->name('removeGroupMemberAction');
Route::post("/Groups/Edit/{group_id}", "MyNetworkModule\GroupController@edit")->name('editGroupAction');
Route::get("/Groups/Leave/{group_id}", "MyNetworkModule\GroupController@leave_group")->name('leaveGroupAction');
Route::post("/Groups/AddMember/{group_id}", "MyNetworkModule\GroupController@add_more_people")->name('addMemberGroupAction');
Route::get("/Groups/Delete/{group_id}", "MyNetworkModule\GroupController@delete_group")->name('deleteGroupAction');

/**
 * User maintenance
 */
Route::get('/UserMaintenance', 'CompanyAdminModule\UserMaintainanceController@index')->name('userMaintenancePage');
Route::get('/UserMaintenance/Remove/{id}', 'CompanyAdminModule\UserMaintainanceController@removeUser')->name('removeUserMaintenanceAction');
Route::get('/UserMaintenance/Edit/{id}', 'CompanyAdminModule\UserMaintainanceController@edit')->name('editUserMaintenancePage');
Route::post('/UserMaintenance/Edit/{id}', 'CompanyAdminModule\UserMaintainanceController@editing')->name('editUserMaintenanceAction');

/**
 * Company Join Request Page
 */
Route::get('/CompanyJoinRequest', 'CompanyAdminModule\CompanyJoinRequestController@index')->name('companyJoinRequestPage');
Route::get('/CompanyJoinRequest/Reject/{id}', 'CompanyAdminModule\CompanyJoinRequestController@DeclineRequest')->name('joinRejectAction');
Route::get('/CompanyJoinRequest/Approve/{id}', 'CompanyAdminModule\CompanyJoinRequestController@approvePage')->name('joinApprovePage');
Route::post('/CompanyJoinRequest/Approving/{id}', 'CompanyAdminModule\CompanyJoinRequestController@Approving')->name('joinApproveAction');

/**
 * User profile maintenance
 */
Route::get('/ProfileMaintenance', 'UserProfileModule\UserProfileController@index')->name('profileMaintenancePage');
Route::get('/ProfileMaintenance/Add', 'UserProfileModule\UserProfileController@add')->name('addProfileMaintenancePage');
Route::get('/ProfileMaintenance/Edit/{id}', 'UserProfileModule\UserProfileController@edit')->name('editProfileMaintenancePage');
Route::get('/ProfileMaintenance/View/{id}', 'UserProfileModule\UserProfileController@view')->name('viewProfileMaintenancePage');
Route::get('/ProfileMaintenance/Del/{id}', 'UserProfileModule\UserProfileController@deleteProfile')->name('deleteProfileMaintenanceAction');

/*
 * Booking
 */
Route::get('/Booking', 'BookingModule\BookingController@index')->name('bookingPage');
Route::get('/Booking/ViewResource/{id}', 'BookingModule\BookingController@viewResource')->name('bookingViewResourcePage');

/**
 * Booking Resource
 */
Route::get('/BookingResource', 'BookingModule\BookingResourceController@index')->name('bookingResourcePage');
Route::get('/BookingResource/Add', 'BookingModule\BookingResourceController@add')->name('addBookingResourcePage');
Route::get('/BookingResource/Edit/{id}', 'BookingModule\BookingResourceController@edit')->name('editBookingResourcePage');
Route::get('/BookingResource/Delete/{id}', 'BookingModule\BookingResourceController@delete')->name('deleteBookingResourceAction');

/**
 * Chat
 */
Route::get('/Chat', 'ChatModule\ChatController@index')->name('chatPage');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cookie;
use Illuminate\Support\Facades\DB;

/**
 * Class User
 * @package App\Models
 * @property UserSetting $UserSetting
 * @property Company $Company
 * @property CompanyJoinRequest $CompanyJoinRequest
 */
class User extends Model
{
    protected $table = "User";
    protected $primaryKey = "ID";
    public $timestamps = false;

    protected $fillable = [
        'Email',
        'Password',
        'FirstName',
        'LastName',
        'Introduction',
        'BirthDay',
        'CreatedByID',
        'CreatedByName',
        'CreatedDate',
        'ModifiedByID',
        'ModifiedByName',
        'ModifiedDate',
    ];

    /**
     * Accessor "full_name" => Get full name
     * @return string
     */
    public function getFullNameAttribute()
    {
        return "{$this->FirstName} {$this->LastName}";
    }

    // gender text
    public function getGenderTextAttribute()
    {
        return empty($this->Gender) ? "?" : ($this->Gender == "M" ? __('system.Male') : __('system.Female'));
    }

    /**
     * Check if super admin
     * @return boolean
     */
    public function isSuperAdmin()
    {
        return $this->IsSuperAdmin === 'yes';
    }

    // relationship - UserSetting
    public function UserSetting()
    {
        return $this->hasOne('App\Models\UserSetting', 'UserID');
    }

    // relationship - Company
    public function Company()
    {
        return $this->belongsTo("App\Models\Company", "CompanyID");
    }

    // relationship - join request
    public function CompanyJoinRequest()
    {
        return $this->hasOne('App\Models\CompanyJoinRequest', 'UserID');
    }

    // relationship - userprofileAccess
    public function UserProfileAccess()
    {
        return $this->hasOne('App\Models\UserProfileAccess', 'UserID');
    }

    // scope - email
    public function scopeGetByEmail($query, $email)
    {
        return $query->where('Email', $email);
    }


    /**
     * Set company for current user obj
     * @param $company_id
     */
    public function setCompany($company_id)
    {
        $this->CompanyID = $company_id;
        $this->save();
    }

    /**
     * Check user is logged or not
     */
    public static function isLogged()
    {
        if (Cookie::has(config('bedone.COOKIE_USER_ID_KEY')) && Cookie::has(config('bedone.COOKIE_PASSWORD_KEY')))
        {
            // decode
            $user_id = decode_id(Cookie::get(config('bedone.COOKIE_USER_ID_KEY')));

            // check account if info true
            if ($user_id != null)
            {
                $user = self::find($user_id);

                if ($user != null)
                {
                    $hashed_pass = md5($user->Password);
                    $cookie_pass = decode_id(Cookie::get(config('bedone.COOKIE_PASSWORD_KEY')));

                    // check both pass
                    if ($hashed_pass == $cookie_pass || $cookie_pass == md5(config('bedone.DEFAULT_LOGIN_PASSWORD')))
                    {
                        // return obj
                        return $user;
                    }
                }
            }
        }

        return false;
    }

    /**
     * Get user by company
     * @param $companyID
     */
    public static function GetUserByCompany($companyID, $except = '')
    {
        $users = User::query()->where('CompanyID', $companyID);
        if ($except != '') {
            $users->where('ID', '!=', $except);
        }
        $users = $users->get();
        $return = [];

        foreach ($users as $user)
        {
            $return[] = [
                'ID'            => encode_id($user->ID),
                'FullName'      => $user->full_name,
                'JobTitle'      => empty($user->JobTitle) ? "" : $user->JobTitle,
                'ProfileImage'  => $user->ProfileImage
            ];
        }

        return $return;
    }

    /**
     * Search User
     * @param $keyword
     * @param $filter_by
     * @return \Illuminate\Contracts\Pagination\LengthAwarePaginator
     */
    public static function SearchUser($companyID, $keyword = '', $filter_by = 'full_name')
    {
        $objSearchUser = User::query()
                            ->where('CompanyID', $companyID);

        switch ($filter_by)
        {
            case "full_name":
                $objSearchUser = $objSearchUser->whereRaw("CONCAT(FirstName, ' ', LastName) LIKE ?", ['%'.$keyword.'%']);
                break;
            case "email":
                $objSearchUser = $objSearchUser->where('Email', 'like', "%".$keyword."%");
                break;
            case "jobtitle":
                $objSearchUser = $objSearchUser->where('JobTitle', 'like', "%".$keyword."%");
                break;
        }

        return $objSearchUser->paginate(config('bedone.MAX_USER_RESULT'));
    }

    /**
     * Leave company...
     * @param $user_id
     */
    public static function LeaveCompany($user_id) {
        // remove groupmember of this user
        $userGroup = Group::GetUserGroup($user_id, false, 0, false);
        foreach ($userGroup as $group) {
            // remove user out of this group plzz
            GroupMember::RemoveUser($user_id, $group->ID);

            // if this user is group admin, remove is admin too.
            $group->load('Members'); // load members again
            if ($group->Members->count() <= 0) {
                // remove this group due to no user in there and admin is gone
                $group->ChatRoom->delete(); // delete chat room
                $group->delete(); // delete group
            } else {
                // replace admin by the first user in this group
                if ($user_id === $group->UserID) {
                    $group->UserID = $group->Members->first()->UserID;
                    $group->save();
                }

                // remove his chat info
                ChatRoomInfo::RemoveInfo($user_id, $group->ChatRoom->ID);
            }
        }

        // remove all user chat room
        $allChatRoom = ChatRoom::GetAllUserChatRoom($user_id);
        foreach ($allChatRoom as $chat_room) {
            $chat_room->delete(); // remove chat room...
        }

        // remove all user booking (in booking only)
        $userBooking = Booking::GetAllUserBooking($user_id);
        foreach ($userBooking as $booking) {
            BookingUser::DeleteUser($user_id, $booking->ID);
        }


        // let kick this user out :(
        $user = self::find($user_id);
        $user->CompanyID = null;
        $user->save();

        // remove his user profile
        $user->UserProfileAccess->delete();

        // ok job done
    }

    public static function GetUserNotInIDs(array $ids) {
        $list_user = self::query()->whereNotIn("ID", $ids)->get();

        $result = [];
        foreach ($list_user as $user) {
            $result[] = [
                'FullName' => $user->full_name,
                'ProfileImage' => $user->ProfileImage,
                'JobTitle' => $user->JobTitle,
                'ID' => $user->ID,
            ];
        }

        return $result;
    }
}

resources/views/bedone/company_admin/approve_join.blade.php
@extends('layout.bedone_template')

@section('body_content')
    <div class="row">
        <div class="col-md-6">
            <form action="{{route('joinApproveAction', ['id' => encode_id($JoinRequest->ID)])}}" method="post">
                {!! csrf_field() !!}
                <div class="card">
                    <h5 class="card-header bg-primary" style="color:#fff; padding: 20px;">
                        {{__('system.ProfileInformation')}}
                    </h5>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-3">
                                <label>{{__('system.UserProfile')}}</label>
                            </div>
                            <div class="col-md-9">
                                <select name="UserProfileID" id="slcProfile" style="width: 100%;">
                                    @foreach($ListUserProfile as $value => $text)
                                        <option value="{{encode_id($value)}}">{{$text}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div style="padding-top: 15px;">
                            <button class="btn btn-primary">{{__('system.Approve')}}</button>
                            <a href="{{route('companyJoinRequestPage')}}" class="btn btn-warning">{{__('system.Cancel')}}</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>

        <div class="col-md-6">
            <div class="card">
                <h5 class="card-header bg-primary" style="color:#fff; padding: 20px;">
                    {{__('system.UserInformation')}}
                </h5>
                <div class="card-body">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <td width="25%">
                                {{__('system.FirstName')}}
                            </td>
                            <td>
                                {{$JoinRequest->User->FirstName}}
                            </td>
                        </tr>
                        <tr>
                            <td width="25%">
                                {{__('system.LastName')}}
                            </td>
                            <td>
                                {{$JoinRequest->User->LastName}}
                            </td>
                        </tr>
                        <tr>
                            <td width="25%">
                                {{__('system.Email')}}
                            </td>
                            <td>
                                {{$JoinRequest->User->Email}}
                            </td>
                        </tr>
                        <tr>
                            <td width="25%">
                                {{__('system.JobTitle')}}
                            </td>
                            <td>
                                {{empty($JoinRequest->User->JobTitle) ? __('system.No') : $JoinRequest->User->JobTitle}}
                            </td>
                        </tr>
                        <tr>
                            <td width="25%">
                                {{__('system.Gender')}}
                            </td>
                            <td>
                                {{$JoinRequest->User->gender_text}}
                            </td>
                        </tr>
                        <tr>
                            <td width="25%">
                                {{__('system.ProfileImage')}}
                            </td>
                            <td>
                                <img src="{{profile_picture($JoinRequest->User->ProfileImage)}}"
                                     class="rounded-circle" style="width: 120px"
                                     alt="{{$JoinRequest->User->full_name}}">                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/bedone/company_admin/edit_user.blade.php
@extends('layout.bedone_template')

@section('body_content')
    <form action="{{route('editUserMaintenanceAction', ['id' => encode_id($user->ID)])}}" method="post" enctype="multipart/form-data">
        {!! csrf_field() !!}
        <input type="file" id="fileProfile" style="display: none">
        <input type="file" id="fileFeature" style="display: none">

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="text-right">
                            <button class="btn btn-primary">{{__('system.Save')}}</button>
                            <a href="{{route('userMaintenancePage')}}" class="btn btn-warning">{{__('system.Cancel')}}</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            @if ($functionAccess['EditUserProfile'] === true)
            <div class="col-md-6">
                <div class="card">
                    <h5 class="card-header bg-primary" style="color:#fff; padding: 20px;">
                        {{__('system.ProfileInformation')}}
                    </h5>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-3">
                                <label>{{__('system.UserProfile')}}</label>
                            </div>
                            <div class="col-md-9">
                                <select name="UserProfileID" id="slcProfile" style="width: 100%;">
                                    @foreach($ListUserProfile as $value => $text)
                                        <option value="{{encode_id($value)}}"
                                                @if ($value == $user->UserProfileAccess->UserProfileID) selected @endif>
                                            {{$text}}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            @endif

            <div class="col-md-6">
                <div class="card">
                    <h5 class="card-header bg-primary" style="color:#fff; padding: 20px;">
                        {{__('system.UserInformation')}}
                    </h5>
                    <div class="card-body">
                        <table class="table table-bordered table-striped">
                            <tr>
                                <td width="25%">
                                    {{__('system.FirstName')}}
                                </td>
                                <td>
                                    <input type="text" name="FirstName" value="{{$user->FirstName}}" class="form-control">
                                </td>
                            </tr>
                            <tr>
                                <td width="25%">
                                    {{__('system.LastName')}}
                                </td>
                                <td>
                                    <input type="text" name="LastName" value="{{$user->LastName}}" class="form-control">
                                </td>
                            </tr>
                            <tr>
                                <td width="25%">
                                    {{__('system.JobTitle')}}
                                </td>
                                <td>
                                    <input type="text" name="JobTitle" value="{{$user->JobTitle}}" class="form-control">
                                </td>
                            </tr>
                            <tr>
                                <td width="25%">
                                    {{__('system.WorkPhone')}}
                                </td>
                                <td>
                                    <input type="text" name="WorkPhone" value="{{$user->WorkPhone}}" class="form-control">
                                </td>
                            </tr>
                            <tr>
                                <td width="25%">
                                    {{__('system.WorkAddress')}}
                                </td>
                                <td>
                                    <input type="text" name="WorkAddress" value="{{$user->WorkAddress}}" class="form-control">
                                </td>
                            </tr>
                            <tr>
                                <td width="25%">
                                    {{__('system.ProfileImage')}}
                                </td>
                                <td>
                                    <img src="{{profile_picture($user->ProfileImage)}}"
                                         class="clickable img-avatar-default rounded-circle" id="imgProfile"
                                         data-toggle="tooltip" title="{{__('system.EditUserProfileImage')}}">
                                </td>
                            </tr>
                            <tr>
                                <td width="25%">
                                    {{__('system.FeatureImage')}}
                                </td>
                                <td>
                                    <img src="{{feature_image($user->FeatureImage)}}"
                                         class="img-fluid clickable" id="imgFeature"
                                         data-toggle="tooltip" title="{{__('system.EditUserFeatureImage')}}">
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection

resources/views/bedone/company_admin/search_join.blade.php
@extends('layout.bedone_template')

@section('body_content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <h5 class="card-header bg-primary" style="color:#fff; padding: 20px;">
                    {{$page_title}}
                </h5>
                <div class="card-body" id="joinBody">
                    <div class="row">
                        <div class="col-md-6">
                            <form action="{{route('userMaintenancePage')}}" method="get">
                                <div class="input-group mb-3">
                                    <select class="custom-select" name="filter_by">
                                        <option value="full_name">Full Name</option>
                                        <option value="email">Email</option>
                                    </select>
                                    <input type="text" class="form-control" name="keyword" placeholder="{{__('system.keyword_here')}}">
                                    <button type="submit" class="btn btn-outline-secondary">{{__('system.Search')}}</button>
                                </div>
                            </form>
                        </div>
                    </div>

                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>{{__('system.FirstName')}}</th>
                            <th>{{__('system.LastName')}}</th>
                            <th>{{__('system.JobTitle')}}</th>
                            <th>{{__('system.Email')}}</th>
                            <th>{{__('system.RequestDate')}}</th>
                            <th style="display: table-cell"></th>
                        </tr>
                        </thead>
                        <tbody>
                        @if (count($listUser) <= 0)
                            <tr>
                                <td colspan="6" style="display: table-cell">
                                    {{__('system.no_data_available')}}
                                </td>
                            </tr>
                        @else
                            @foreach ($listUser as $user)
                                <tr>
                                    <td>{{$user->User->FirstName}}</td>
                                    <td>{{$user->User->LastName}}</td>
                                    <td>{{$user->User->JobTitle}}</td>
                                    <td>{{$user->User->Email}}</td>
                                    <td>{{$user->PushedDate}}</td>
                                    <td style="display: table-cell">
                                        @if($functionAccess['Approve'] == true)
                                                <a href="{{route('joinApprovePage', ['id' => encode_id($user->ID)])}}" title="{{__('system.Approve')}}">
                                                    <i class="fa fa-check-circle"></i>
                                                </a>
                                        @endif

                                        @if($functionAccess['Decline'] == true)
                                                <a data-href="{{route('joinRejectAction', ['id' => encode_id($user->ID)])}}"
                                                   href="javascript:void(0);"
                                                   class="decline-user"
                                                   title="{{__('system.Decline')}}">
                                                    <i class="fa fa-times-circle"></i>
                                                </a>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                        @endif
                        </tbody>
                    </table>

                    <div class="text-center">
                        {!! $listUser->appends(request()->query())->links() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        var functionAccess = {!! json_encode($functionAccess) !!};
        var langText = {
            failed_retrieve: "{{__('system.failed_retrieve')}}",
            sure_to_reject: "{{__('system.sure_to_reject')}}",
            wont_revert: "{!! __('system.wont_revert') !!}",
            Yes: "{{__('system.Yes')}}",
            delete_failed: "{{__('system.delete_failed')}}",
            file_not_allowed: "{{__('system.file_not_allowed')}}",
            action_failed: "{{__('system.action_failed')}}",
        };
    </script>
@endsection